name: on_popup_window_widget
description: "An awesome popup widget that fulfills all your demands in dialog. Supports material 3" 
version: 0.0.7
homepage: https://github.com/SHAJED99/on_popup_window_widget
license: BSD 3-Clause

# -------------------
screenshots:
  - description: 'Example of on_popup_window_widget'
    path: screenshots/1.gif

# -------------------
topics:
  - popup-window
  - dialog

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
