name: on_popup_window_widget
description: "A new Flutter package project." 
version: 0.0.1
homepage: https://github.com/SHAJED99/on_process_button_widget
license: BSD 3-Clause

# // -------------------
# screenshots:
#   - description: 'Example of on_process_button_widget'
#     path: screenshots/all.gif

# // -------------------
# topics:
#   - button 
#   - elevated-button
#   - animated-button

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
